version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: div1neikk/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    env_file: .env
    image: div1neikk/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    depends_on:
      - backend
      - nginx
  nginx:
    image: nginx:1.22.1
    ports:
      - "6555:80"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - static:/static
      - media:/media
    depends_on:
      - backend