# Generated by Django 4.2.3 on 2024-04-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_shoppingcart_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usersrecipesfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='user_recipe_favorite_unique'),
        ),
    ]
